import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import { cookies } from "next/headers";
import SearchModalEventListener from "./components/Wrapper/SearchModalEventListener";
import Layout from "./components/common/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme");

  return (
    <html
      lang="ko"
      data-theme={
        theme === undefined
          ? "cupcake"
          : theme.value === "light"
          ? "cupcake"
          : "dracula"
      }>
      <body>
        <SearchModalEventListener>
          <Header />
          <Layout>{children}</Layout>

          <Footer />
        </SearchModalEventListener>
      </body>
    </html>
  );
}
